services:
  front:
    image: transcendence_front
    container_name: transcendence_front
    build: ../src/frontend/
    restart: always
    env_file: .env-dev
    ports:
      - "8080:8080"
    volumes:
      - ../src/frontend/:/app
      - /app/node_modules
      - /app/.next
    networks:
      - transcendence-net
  
  api:
    image: transcendence_api
    container_name: transcendence_api
    build: ../src/backend/api/
    restart: always
    env_file: .env-dev
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    ports:
      - "3000:3000"
    volumes:
      - ../src/backend/api:/api
      - /api/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence-net

  db:
    image: transcendence_db
    container_name: transcendence_db
    build: ../src/backend/db/
    env_file: .env-dev
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - transcendence-net

  adminer:
    image: adminer:5.4.2
    container_name: transcendence_adminer
    env_file: .env-dev
    ports:
      - "8081:8080"
    networks:
      - transcendence-net

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge

volumes:
  db-data:
    name: db-data
