services:
  front:
    build:
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ../frontend/:/app
      - frontend-node-modules:/app/node_modules
    networks:
      - transcendence-net
    command: bun run dev
  
  api:
    build:
      target: dev
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      CHOKIDAR_USEPOLLING: "true" # To avoid hot reload problem
    ports:
      - "3000:3000"
    volumes:
      - ../backend/api:/api
      - api-node-modules:/api/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence-net
    command: sh -c "bunx prisma generate && bunx prisma migrate deploy && bun run start:dev"

  db:
    ports:
      - "5433:5432"
    networks:
      - transcendence-net

  adminer:
    image: adminer:5.4.2
    container_name: transcendence_adminer
    env_file: .env
    ports:
      - "8081:8080"
    networks:
      - transcendence-net

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge

volumes:
  frontend-node-modules:
    name: transcendence-frontend-node-modules
  api-node-modules:
    name: transcendence-api-node-modules
