services:
  front:
    image: transcendence_front
    container_name: transcendence_front
    pull_policy: build
    build:
      context: ../frontend/
      target: prod
    restart: always
    env_file: .env
  
  api:
    image: transcendence_api
    container_name: transcendence_api
    pull_policy: build
    build:
      context: ../backend/api/
      target: prod
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    depends_on:
      - db
      
  db:
    image: transcendence_db
    container_name: transcendence_db
    pull_policy: build
    build: ../backend/db/
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql

  proxy:
    image: caddy:2.11-alpine
    container_name: transcendence_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - front
      - api


volumes:
  db-data:
    name: transcendence-db-data
  caddy-data:
    name: transcendence-caddy-data
  caddy-config:
    name: transcendence-caddy-config
